version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: scheduler-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scheduler-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: scheduler-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - scheduler-network

networks:
  scheduler-network:
    driver: bridge

volumes:
  postgres_data: 